version: "2"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermos
      # set amazon s3 information
      # - MM_DRIVER_NAME=
      # - MM_AMAZON_S3_BUCKET=
      # - MM_AMAZON_S3_REGION=us-west-2
      # - MM_AMAZON_S3_ACCESS_KEYID=
      # - MM_AMAZON_S3_SECRET_ACCESS_KEY=
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
    ports:
      - "30080:8000"
